# Generated by Django 5.2.4 on 2025-07-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='baner')),
                ('image2', models.ImageField(upload_to='baner')),
                ('image3', models.ImageField(upload_to='baner')),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('instagram', models.URLField(null=True)),
                ('rubika', models.URLField(null=True)),
                ('telegram', models.URLField(null=True)),
                ('discreption', models.TextField()),
                ('logo', models.ImageField(upload_to='logo')),
                ('name1', models.CharField(max_length=50)),
                ('perseneImage1', models.ImageField(upload_to='modiriat')),
                ('name2', models.CharField(max_length=50)),
                ('perseneImage2', models.ImageField(upload_to='modiriat')),
                ('name3', models.CharField(max_length=50)),
                ('perseneImage3', models.ImageField(upload_to='modiriat')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='slider')),
            ],
        ),
    ]
