# Generated by Django 5.2.4 on 2025-07-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_banner_delete_banerimage_delete_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': ' اسلایدر و بنرها', 'verbose_name_plural': 'اسلایدر و بنر '},
        ),
        migrations.AlterModelOptions(
            name='siteinfo',
            options={'verbose_name': ' اطلاعات سایت و پرسنل', 'verbose_name_plural': ' اطلاعات سایت و پرسنل'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='لینک '),
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='اولویت نمایش'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('main', 'اسلایدر اصلی'), ('sidebar', 'بنر کنار اسلایدر'), ('footer', 'بنر پایین صفحه')], max_length=50, verbose_name='جایگاه'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='discreption',
            field=models.TextField(verbose_name='توضیحات سایت'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='instagram',
            field=models.URLField(null=True, verbose_name='ایدی اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='logo',
            field=models.ImageField(upload_to='logo', verbose_name='لگوی سایت'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='name1',
            field=models.CharField(max_length=50, verbose_name='نام پرسنل ۱'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='name2',
            field=models.CharField(max_length=50, verbose_name='نام پرسنل۲'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='name3',
            field=models.CharField(max_length=50, verbose_name='نام پرسنل۳'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='perseneImage1',
            field=models.ImageField(upload_to='modiriat', verbose_name='عکس پرسنل ۱'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='perseneImage2',
            field=models.ImageField(upload_to='modiriat', verbose_name='عکس پرسنل۲'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='perseneImage3',
            field=models.ImageField(upload_to='modiriat', verbose_name='عکس پرسنل۳'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='شماره پشتیبانی'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='rubika',
            field=models.URLField(null=True, verbose_name='ایدی روبیکا'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='telegram',
            field=models.URLField(null=True, verbose_name='ایدی تلگرام'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان سایت'),
        ),
    ]
