# Generated by Django 5.2.4 on 2025-07-05 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_slider_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='Image',
            new_name='image',
        ),
    ]
