# Generated by Django 5.2.4 on 2025-07-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_rename_image_slider_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='banners/')),
                ('link', models.URLField(blank=True, null=True)),
                ('position', models.CharField(choices=[('main', 'بنر اصلی'), ('sidebar', 'سایدبار'), ('footer', 'بنر پایین صفحه')], max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='banerImage',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
