# Generated by Django 5.2.4 on 2025-07-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='token',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
