# Generated by Django 5.2.4 on 2025-08-05 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_addressmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressmodel',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس ها  '},
        ),
        migrations.RemoveField(
            model_name='addressmodel',
            name='user1',
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='full_name',
            field=models.CharField(default=0, max_length=50, verbose_name='نام کامل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='address',
            field=models.CharField(max_length=300, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='postal_code',
            field=models.CharField(max_length=16, verbose_name='کد پستی'),
        ),
    ]
