# Generated by Django 5.2.4 on 2025-08-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_alter_addressmodel_options_remove_addressmodel_user1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='phone',
            field=models.CharField(default=0.6695, max_length=12, verbose_name='شماره تلفن تحویل گیرنده'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='address',
            field=models.TextField(max_length=300, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='full_name',
            field=models.CharField(verbose_name='نام تحویل گیرنده'),
        ),
    ]
