# Generated by Django 5.2.4 on 2025-07-07 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catigory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('all_discount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='produc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('name_to_english', models.CharField(max_length=50)),
                ('firest_price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_image')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('catigory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products_app.catigory')),
            ],
        ),
    ]
