# Generated by Django 5.2.4 on 2025-07-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_produc_likes_produc_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produc',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
