# Generated by Django 5.2.4 on 2025-07-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_alter_produc_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catigory',
            name='all_discount',
            field=models.IntegerField(default=0),
        ),
    ]
