# Generated by Django 5.2.4 on 2025-07-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0004_alter_catigory_all_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catigory',
            name='all_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
