# Generated by Django 5.2.4 on 2025-07-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0005_alter_catigory_all_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produc',
            name='likes',
            field=models.IntegerField(default=0, help_text='max Like is 30'),
        ),
    ]
