# Generated by Django 5.2.4 on 2025-07-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0007_alter_produc_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catigory',
            name='all_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produc',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
