# Generated by Django 5.2.4 on 2025-07-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0008_alter_catigory_all_discount_alter_produc_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='produc',
            name='number_of_pruduct',
            field=models.IntegerField(default=0),
        ),
    ]
