# Generated by Django 5.2.4 on 2025-07-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0009_produc_number_of_pruduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='produc',
            name='number_of_pruduct_remaint',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produc',
            name='number_of_pruduct_sold',
            field=models.IntegerField(default=0),
        ),
    ]
