# Generated by Django 5.2.4 on 2025-07-11 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0010_produc_number_of_pruduct_remaint_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='catigory',
            new_name='Category',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('name_to_english', models.CharField(max_length=50)),
                ('base_price', models.IntegerField(help_text='قیمت پایه بدون تخفیف')),
                ('discount', models.IntegerField(default=0, help_text='درصد تخفیف محصول')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_image')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('pack', 'Pack'), ('pcs', 'Piece')], default='kg', max_length=10)),
                ('unit_amount', models.DecimalField(decimal_places=2, default=1, help_text='مقدار واحد (مثلاً 0.5 برای بسته نیم کیلو)', max_digits=5)),
                ('stock_quantity', models.DecimalField(decimal_places=3, default=0, help_text='موجودی انبار', max_digits=10)),
                ('sales_count', models.PositiveIntegerField(default=0, help_text='تعداد فروش')),
                ('likes', models.PositiveIntegerField(default=0, help_text='حداکثر 30 لایک')),
                ('selected', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products_app.category')),
            ],
        ),
        migrations.DeleteModel(
            name='produc',
        ),
    ]
