# Generated by Django 5.2.4 on 2025-07-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0011_rename_catigory_category_product_delete_produc'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
