# Generated by Django 5.2.4 on 2025-07-23 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0012_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': ' دسته بندی ', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': ' محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterField(
            model_name='category',
            name='all_discount',
            field=models.IntegerField(default=0, verbose_name='تخفیف برای تمام محصولات این دسته '),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, verbose_name='دسته بندی '),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(verbose_name='دسته بندی به انگلیسی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.IntegerField(help_text='قیمت پایه بدون تخفیف', verbose_name='قیمت پایه '),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products_app.category', verbose_name='دسته'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, help_text='درصد تخفیف محصول', verbose_name='تخفیف برای این محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products_image', verbose_name='عکس محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='likes',
            field=models.PositiveIntegerField(default=0, help_text='حداکثر 30 لایک', verbose_name='تعداد لایک ها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=40, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_to_english',
            field=models.CharField(max_length=50, verbose_name='نام انگلیسی محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_count',
            field=models.PositiveIntegerField(default=0, help_text='تعداد فروش', verbose_name='مقدار فروش رفته'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selected',
            field=models.BooleanField(default=True, verbose_name='انتخاب شده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=0, default=0, help_text='موجودی انبار', max_digits=10, verbose_name='موجودی انبار'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('pack', 'Pack'), ('pcs', 'Piece')], default='kg', max_length=10, verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_amount',
            field=models.DecimalField(decimal_places=2, default=1, help_text='مقدار واحد (مثلاً 0.5 برای بسته نیم کیلو)', max_digits=5, verbose_name='مقدار وزن هر بسته'),
        ),
    ]
