# Generated by Django 5.2.4 on 2025-07-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0013_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discription',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
