# Generated by Django 5.2.4 on 2025-08-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
