# Generated by Django 5.2.4 on 2025-09-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0004_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(blank=True, null=True, verbose_name='مجموع'),
        ),
    ]
