# Generated by Django 5.2.4 on 2025-09-24 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0005_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
