# Generated by Django 5.2.4 on 2025-09-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0007_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
    ]
